オブジェクト指向のボーリング課題の提出
R-Tsukada/ruby-practices pull request #1
Opened 2021-05-29 00:54 UTC by R-Tsukada

オブジェクト指向版のボーリング課題を作成しました。お手隙の際にご確認とレビューをしていただけると幸いです。

【お願いしたいこと】
・コードがかなり力技になっていて、読みにくいコードになっていると思います🙇‍♂️リファクタリングのアドバイスもいただけたらと思います。

【gameクラスのコードの説明】
gameクラスの条件分岐が、意図のわかりにくいコードになっていると思います。なので条件分岐の条件とコードの意図を書いておきます。

・17-18行目：最終フレームがストライクだった場合、最終フレームの第2投を追加する（最終フレームなので、最終フレームの2投目がボーナスショットの扱いになるため）
・19-20行目：次のフレームもストライクかつ最終フレームじゃない
・21-22行目：次のフレームがスペアだった場合（`@frames[n + 1].score`では最終フレームのボーナスショットの点も加点されるため）
・26-27行目：スペアかつ最終フレームじゃない（最終フレームのボーナスは14行目の`score += @frames[n].score`で追加できるため）

2021-05-31 15:04 UTC, torinoko reviewed
@R-Tsukada 
ごめんなさい！全部見切れなかったのですが一回お返しします。

クラス名とメソッド名、変数名で被っているものが多いところが少し気になりました。
もしかしたら命名でもうちょっと工夫できるかもしれません。
具体的な名前にできるところがないか見直してみていただけますか 🙏

2021-05-31 15:04 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +    end
一番気になっているのはここですよね。
条件をもう少し整理したいですね〜。
考えていたら時間が遅くなってしまったので一回持ち帰らせてください 🙏 

`#srike?` や `#spare?` や `n` の比較が複数箇所に出てくるので、この辺りもう少しまとめられそうな気配はありますよね。

2021-05-31 15:04 UTC, torinoko commented on 07.bowling_object/lib/mark.rb
> +  attr_reader :mark
この `mark` は外部から参照されますか？

2021-06-02 13:08 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +    end
込み入った処理を `if @frames[n].strike?` の外に出してみるのはどうでしょうか。
ストライクとスペアのときに獲得できるポイントを、あらかじめ計算しておくとよさそうに思いました。ストライクとスペアのときには計算済みのポイントを足すだけにする感じです。

手元で書き直したところ、最終的にはこんな感じになりました。
```ruby
      points = []

      # 何らかの処理

      if @frames[n].strike?
        score += points.sum
      elsif @frames[n].spare?
        score += points[0]
      end
```

私がリファクタリングのために考えたことを書いておきますね。

- score に代入する処理が複雑になっている 👀 
  - 複雑……なのでメソッドなどにすることは可能か？
    - そのままメソッドにするだけでは複雑さがあまり変わらない気がした
  - では、ここではないところで計算することは可能だろうか？
- 条件に該当するときは基本的に `@frames[n + 1].first_mark.score` が足されている 👀 
  - これはヒントになりそうな気がした
  - `n == 9` のときは second_mark を足しているけどいったん忘れる
- あらかじめ計算しておいて、ストライクかスペアの判定時に使う値を決めればいいかも？ 🤔 
  - ストライクのときは全部足す
  - スペアのときは first_mark だけ足す……とかどうだろうか 🤔 

もちろん他にも解き方はあるので、上は参考程度にしていただけるといいかなと思います。

2021-06-11 07:34 UTC, R-Tsukada commented on 07.bowling_object/lib/mark.rb
> +  attr_reader :mark
標準入力で出力される値が`mark`なので、そこで外部から参照されると思っています。
間違った考え方をしていたらご指摘ください🙇‍♂️

<img width="641" alt="07_bowling_object_–_mark_rb" src="https://user-images.githubusercontent.com/62058863/121648589-a11e6a00-cad2-11eb-88b6-aaec37793a0d.png">

2021-06-11 07:34 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +# game
コメントを削除しました。

2021-06-11 07:34 UTC, R-Tsukada commented on 07.bowling_object/lib/frame.rb
> +
改行を削除しました。

2021-06-11 07:35 UTC, R-Tsukada commented on 07.bowling_object/lib/mark.rb
> +  attr_reader :mark
標準入力の値が`mark`なので、そこで参照されると思っています。
もし間違った解釈でしたら、ご指摘ください🙇‍♂️

<img width="641" alt="07_bowling_object_–_mark_rb" src="https://user-images.githubusercontent.com/62058863/121648986-0b370f00-cad3-11eb-9097-897c84460634.png">

2021-06-11 07:36 UTC, R-Tsukada commented on 07.bowling_object/lib/frame.rb
> +end
末尾に改行を入れました。

2021-06-11 07:38 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +    end
> 込み入った処理を if @frames[n].strike? の外に出してみるのはどうでしょうか。

自分なりの解釈でコードを作成したのですが、いかがでしょうか。
条件分岐がわかりにくくなってしまったのでコメントをつけています。

ご確認よろしくお願いします🙇‍♂️

2021-06-11 07:39 UTC, R-Tsukada commented on 07.bowling_object/lib/frame.rb
> +  end
ありがとうございます🙇‍♂️

2021-06-11 14:53 UTC, torinoko reviewed
@R-Tsukada 
複雑なところをいったん切り出せたのは前進ですね 👍 
もう少し条件や処理をすっきりさせることができそうです。

あと今のコードは私の手元だとエラーが出て動かなかったのですが、R-Tsukada さんの環境では大丈夫でしたか？（私の環境のせいだったらごめんなさい！）

2021-06-11 14:53 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +                end
`if` のネストがひとつ減りましたね 💡 
もうちょっと条件や処理をすっきりさせられそうです。
以下に注目してみましょうか。

- ポイントを36-40行目で加算している
- 加算される場合、最初の値は基本的に `@frames[n + 1].first_mark.score` である

なので私ならここで `strike?` やフレーム数の判定は行わずにこう書くかなと思います。
```ruby
points = []
points << (@frames[n + 1]&.first_mark&.score || 0)
```

ぼっち演算子 `&.` をつけているのは、最終フレームで n + 1 個目のフレームがない場合を想定しています。最終フレームの場合は nil になるので、 `first_mark` や `score` を呼び出せなくなります。で、score の方が nil の場合は 0 を代入するように書いています。

次は @R-Tsukada さんも書いていらっしゃるように、 `n < 9` の最終フレームじゃない場合と最終フレームの場合ですね 🎳 
```ruby
if n < 9
  if @frames[n - 1]&.strike?
    points << 10  # 前のフレームもストライクなら10pt加算
  else
    points << (@frames[n + 1]&.second_mark&.score || 0)
  end
end
```

こんな感じでいかがでしょうか？

ぼっち演算子を多用しているのがちょっと気になるところではあります。
あまりお行儀がよい方法ではないからです。
`@frames` 辺りを変えると回避できそうですが、いったんそのままにしました。

2021-06-11 14:53 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +                end
深く長い `if` 文の値を変数に代入することは、基本的に避けるとよさそうです。
避けるためにどうするか？というのが工夫するポイントになったりします 💡

2021-06-11 14:53 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +                end
もしかしたら上記コードでうまく動かない可能性もあるので、その場合は調整を入れていただけると嬉しいです！ 🙏

2021-06-11 14:53 UTC, torinoko commented on 07.bowling_object/lib/mark.rb
> +  attr_reader :mark
なるほど！
ここは `Game` オブジェクトを作るときの引数ですね 💡 `
`Mark` クラスは関係していないかなーと思います。
（名前が同じなのでちょっと混乱しちゃいますね）

2021-06-11 14:53 UTC, torinoko commented on 07.bowling_object/lib/mark.rb
> +    @mark == 'X' ? 10 : @mark.to_i
ここは `attr_reader` があること前提の記述と、ないときの記述が混ざっていますね〜。
チェリー本などでアクセサのところを読み直してみるとよいかもしれません 🍒

2021-06-12 12:17 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +                end
ご提案いただいたコードで上手く動きました！
こんな書き方があるのか！と驚きました。自分では思いつきもしませんでした💦

> ぼっち演算子を多用しているのがちょっと気になるところではあります。
あまりお行儀がよい方法ではないからです。

これはどういった理由なのでしょうか？？
コードが読みにくい等の理由でしょうか？

> @frames 辺りを変えると回避できそうですが、

自分なりに考えてみたのですが、解決策がまったく思いつきませんでした💦
ヒントをいただけると嬉しいです🙇‍♂️

2021-06-12 12:20 UTC, R-Tsukada commented on 07.bowling_object/lib/mark.rb
> +    @mark == 'X' ? 10 : @mark.to_i
> （名前が同じなのでちょっと混乱しちゃいますね）

クラス名を`Mark`から`Shot`に変更してみました。

> ここは attr_reader があること前提の記述と、ないときの記述が混ざっていますね〜。
チェリー本などでアクセサのところを読み直してみるとよいかもしれません 🍒

修正してみました。僕の認識がズレているようでしたご指摘してもらいたいです🙇‍♂️

2021-06-13 14:42 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +                end
@R-Tsukada 
複雑になっているときはバラしてみたり、共通しているところに注目してみると新たな発見があるかもしれません……！
（仕事のコードだとどうしようもないときもあるんですが…… 😇 ）

### ぼっち演算子

そうですね、読みにくいというのももちろんあります〜！
あとは「レシーバが nil のときがある」という状況がよいのかどうか？というところですかね。

今回だと Frame を期待しているのに nil になっているケースがあるので、
できれば別の方法で Frame が存在しないことを確認して、
ぼっち演算子の使用を避ける方がきれいかなーという気がしました。

なので Tsukada さんが書いていたように何投目かをチェックして、
`n+1` がなかったら `0` という処理にするのもありだと思います！

とはいえ言語に備わっている機能なので、気にせず使ったらいいのでは〜という考えもあります ☺️ 
私はここぞというときに使います 💪 
この辺りは好みの問題もあるかもしれませんね 💡 
https://docs.ruby-lang.org/ja/latest/doc/news=2f2_3_0.html


###  Frame 辺りの変え方

いくつかポイントがありそうです 💡 

#### デメテルの法則

たとえば `frame.first_mark.score` のような処理ですが、
厳密にいうと「デメテルの法則」という法則に沿っていません。

「デメテルの法則」は、お隣さんのお隣さんとはお話ししないというものです。

今回、Game クラスは Frame のオブジェクトを参照しています。
これをここでは「Game クラスは Frame オブジェクトとお話ししている」と表現しましょう。

Game クラスから見て、Frame オブジェクトは直接お話ししているお隣さんです。
Game クラスから見ると Frame オブジェクトが呼び出している Shot オブジェクト（first_mark）はお隣さんのお隣さんとなります。

なぜお隣のオブジェクトと話してはいけないのか？というところが気になりますよね。

今回のような `frame.first_mark.score` という参照は、以下の点が気になるポイントになります。

- Game クラスが「Frame クラスが Shot オブジェクトを扱っていること」を知っている
- Game クラスが、直接お話ししていない Shot クラスのメソッドを知っている
- Frame クラスが `attr_reader` を消したりすると Game が壊れる（Frame クラスを変更しづらい）

Game は Frame とお話ししているのに、直接お話ししてない Shot に関する知識まで要求されてしまうんですね。
なので Frame クラスに `first_mark_score` のようなメソッドを作ることも、ひとつの解決方法になります。

……と長々と書いたのですが、これも利点欠点あるので、バランスを考えながらやっていくとよいと思います 👍 
コードを書きながら「お隣さんのお隣さんと話し過ぎていないかな？」というところは気にしてみるとよいです。

#### フレームの前後を取得するメソッドを作る

ぼっち演算子の話と被りますが、以下のような形にするとちょっと読みやすくなるかも？

```ruby
def score
  ...
  @frame.each_with_index do |frame, n|
    score += frames.score
    if next_frame(n) && next_frame(n).strike?
  ...
end

def next_frame(current_number)
  @frames.fetch(current_number + 1, nil)
end
```

2021-06-13 14:50 UTC, torinoko commented on 07.bowling_object/lib/mark.rb
> +    @mark == 'X' ? 10 : @mark.to_i
@R-Tsukada 
`attr_reader` をつけると、以下のメソッドが自動で追加されますね 💡 
```ruby
def mark
  @mark
end
```
https://docs.ruby-lang.org/ja/latest/method/Module/i/attr_reader.html

今回、Shot オブジェクトの mark は外部から参照されていなさそうなので、
`attr_reader` はいらないかな？と思いました。

また、削除されましたが `if`のところでは `@` なしの `mark` 変数を参照していたのに対し、
`@mark.to_i` のところでは `@` ありの `mark` を参照していたので、
どちらかに合わせた方がいいかな？という気がしました。

2021-06-13 14:56 UTC, torinoko reviewed
@R-Tsukada 
修正と質問ありがとうございます！
すみません、ぶわーっと書いてしまい、わかりづらいところもあるかと思います。
しっくりこないようでしたらどんどんコメントください……！ 🙏 
いったん「そういう考え方もあるんだな〜」と流していただいても大丈夫です 👍 

また「こうしたらいいかも？」という案もいくつか書きましたが、今回はこのままでも大丈夫です！
変更されるようでしたら引き続きレビューします 💪 
修正の判断は Tsukada さんにお任せします〜！

2021-06-13 14:56 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +      point = points.flatten
この `#flatten` はなくても動きそうな気がしました！

2021-06-16 13:54 UTC, R-Tsukada commented on 07.bowling_object/lib/mark.rb
> +    @mark == 'X' ? 10 : @mark.to_i
修正しました🙇‍♂️

2021-06-16 13:55 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +                end
> デメテルの法則

書籍で読んだことがありました。書籍を読んでいるときは「なるほど、気をつけよう」と思っていたのですが、いざコードを書き始めるとすっかり失念してしまっていました🙇‍♂️

> フレームの前後を取得するメソッドを作る
ぼっち演算子の話と被りますが、以下のような形にするとちょっと読みやすくなるかも？

ご提案してもらった方法でコードを書き直してみたのですが、うまくできませんでした💦

**うまくできなかった点**
・また条件分岐が長くなってしまった
・連続ストライク時のボーナスに関するコードが適切に書けていません。そのため`test_score4`ではエラーが出てしまっています。正しい結果は`300`なのですが、`310`になっています。

状況を適切に説明することができず、わかりにくくなっていると思います🙇‍♂️💦
大変申し訳ないのですが、またアドバイスをいただけると嬉しいです。

> また「こうしたらいいかも？」という案もいくつか書きましたが、今回はこのままでも大丈夫です！
変更されるようでしたら引き続きレビューします 💪
修正の判断は Tsukada さんにお任せします〜！

自分としてはもう少し頑張りたいと思っています。Rubyの苦手意識がかなりあるので、少しでも知識と考え方を身につけたいです。何度も同じような質問をしてしまっているので、ご迷惑をおかけしていると思いますが、もう少しレビューをしていただけると嬉しいです🙇‍♂️

2021-06-16 13:55 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +      point = points.flatten
削除しました！

2021-06-20 04:22 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +                end
> デメテルの法則

書籍を読んで、こうやって実践することで理解が深まりますよね 💡
`*_bonus` メソッドに閉じ込めたのはとてもいいと思いますー！
これで Game クラスは Shot クラスを意識しなくて済みますね！

> 自分としてはもう少し頑張りたいと思っています。

了解です！
がっつりやりましょう〜！！ 💪 
うまくできなかった点についてもご説明ありがとうございます！
コードの方にコメントしていきますね 📝

2021-06-20 04:23 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +                end
@R-Tsukada 
> デメテルの法則

書籍を読んで、こうやって実践することで理解が深まりますよね 💡
`*_bonus` メソッドに閉じ込めたのはとてもいいと思いますー！
これで Game クラスは Shot クラスを意識しなくて済みますね！

> 自分としてはもう少し頑張りたいと思っています。

了解です！
がっつりやりましょう〜！！ 💪 
うまくできなかった点についてもご説明ありがとうございます！
コードの方にコメントしていきますね 📝

2021-06-20 04:57 UTC, torinoko reviewed
@R-Tsukada 
いくつかコメントしました！
全体的にめちゃくちゃよくなってて素晴らしいと思いますー！ ✨ 
Game から Frame 内の Shot が見えなくなったのがすごくいいですね 👍 
あともう一歩、もう少し！だと思います！

あとコミットの粒度がとてもいいですね〜 ✨ 
贅沢をいうとコミットメッセージに「なぜ」が書かれているともっとよいですね。
たとえば以下のコミットだと「attr_readerメソッドを削除」となっています。
64a604e0253afb3f21767ae9a983bff8113575a0

コミットを見ると、確かに削除されていますね。
このコミットを後から見た人は「なぜ削除されたのだろう？」というところが気になるんじゃないかと思います。なので「外部から参照されないためアクセサメソッドを削除」等、「なぜこういう変更を行なったのか」という理由を書くともっと親切なコミットメッセージになります ☺️ 
ぜひ今後はその辺りも気にしながら書いてみてください〜！

他のコメントは以下です 📝 
https://github.com/R-Tsukada/ruby-practices/pull/1#discussion_r654874158

2021-06-20 04:57 UTC, torinoko commented on 07.bowling_object/lib/frame.rb
> +  attr_reader :first_mark, :second_mark, :third_mark
first_mark, second_mark, third_mark は外部から参照されますか？
必要ないようでしたら `attr_reader` を外しちゃいましょう〜！

2021-06-20 04:57 UTC, torinoko commented on 07.bowling_object/lib/frame.rb
> +  end
ストライクスペアそれぞれのボーナスとしてまとめたのいいですね！
これで Game クラスが気にする必要なくなりましたね ✨

2021-06-20 04:57 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +      score += frame.score
最後の投球のときはボーナスを加算しないので、飛ばしちゃってもよさそうです 💡 
たとえばこんな感じ。
```ruby
next if n >= 9
```
もしくは `next_frame` メソッドを利用してもいいかもしれませんね！
次のフレームがない＝最後の投球とみなすこともできるので可読性もよさそう。
```ruby
next unless next_frame(n)
```
こういう風に判定して、以降の処理をスキップするという処理はよく使います。
この後にに出てくる `if` 文の条件もひとつ減らすこともできますね〜。

2021-06-20 04:57 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +        score += 10 if @frames[n - 1].strike?
第一投目が鍵になっていそうです 🔑 
irb で簡単に再現してみましょうか。
```ruby
frames = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
p frames[0] #=> 一投目は `n` が `0` ですね
p frames[0 - 1] #=> 16行目はこれと似た処理をしていますね
```
どういう結果になったでしょうか。
この結果を見て、どういう処理を書くとよいかイメージついたでしょうか？

2021-06-20 04:57 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +        score += 10
この処理は不要そうですね 💡 
ここの `elsif` の処理に入るのは next_frame のない十投目だけですが、十投目はボーナスがないので、なくても大丈夫そうに思いました。

2021-06-20 04:57 UTC, torinoko commented on 07.bowling_object/lib/game.rb
> +end
このメソッドは使ってなさそうですね 👀

2021-06-29 05:19 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +end
すみません、削除し忘れていました🙇‍♂️💦
削除しました！

2021-06-29 05:19 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +        score += 10
削除しました！

2021-06-29 05:21 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +      score += frame.score
> こういう風に判定して、以降の処理をスキップするという処理はよく使います。

そうなんですね！しっかり覚えておきます。
`next unless next_frame(n)` を使うことにしました！

2021-06-29 05:23 UTC, R-Tsukada commented on 07.bowling_object/lib/game.rb
> +        score += 10 if @frames[n - 1].strike?
torinokoさんの意図したものとは違うかもしれませんが、以下のように修正してみました。
```
score += frame.score

      next unless next_frame(n)

      if frame.strike? && next_frame(n)
        score += next_frame(n).strike_bonus
        score += 10 if @frames[n + 1].strike? #修正した箇所
```
ご確認をお願いします。

2021-06-29 05:25 UTC, R-Tsukada commented
> 「なぜこういう変更を行なったのか」という理由を書くともっと親切なコミットメッセージになります ☺️

そこまで考えていませんでした💦今後は意識するようにしてみます！

2021-07-13 05:56 UTC, komagata requested changes

2021-07-13 05:56 UTC, komagata commented on 07.bowling_object/lib/bowling.rb
> +require './lib/game'
カレントディレクトリからの相対パスを使う場合は`require_relative`を使うといいかもです。
（ちょっとややこしいのでどういうものでなんのために使うのかも調べるといいと思います〜）

2021-07-13 05:56 UTC, komagata commented on 07.bowling_object/lib/game.rb
> +def next_frame(current_number)
クラスを使ってるので、どこにも所属しないメソッドはかなりの理由がないと作らないのでどこかに所属させた方がいいと思います。（いかにも所属できそうな感じでもあるので）

2021-07-13 05:56 UTC, komagata commented on 08.ls_object/lib/run_ls.rb
> +# frozen_string_literal: true
lsのコミットが含まれちゃってるかも？

2021-07-15 05:14 UTC, komagata requested changes

2021-07-15 05:14 UTC, komagata commented on 07.bowling_object/lib/frame.rb
> +  def spare_bonus
bonusという単語が何度かメソッド名に出てくるということは、`Bonus`というクラスを作った方がいいというサインかもです〜

[[RubyTips] 頻出名詞をクラスに抜き出す - komagataのブログ](https://docs.komagata.org/5733)

2021-07-15 05:14 UTC, komagata commented on 08.ls_object/lib/run_ls.rb
> +#require './lib/format.rb'
過去のコードは全てgitでいつでも取り出せるので、コメントアウトで残しておくということは基本しなくて大丈夫です〜

2021-07-22 01:55 UTC, R-Tsukada commented on 08.ls_object/lib/run_ls.rb
> +#require './lib/format.rb'
わかりました！ありがとうございます！

2021-07-22 05:23 UTC, komagata requested changes

2021-07-22 05:23 UTC, komagata commented on 08.ls_object/lib/run_ls.rb
> +#require './lib/format.rb'
こちらまだのこっているみたいです～

2021-07-22 07:25 UTC, R-Tsukada commented on 08.ls_object/lib/run_ls.rb
> +#require './lib/format.rb'
削除しました🙇‍♂️💦
ご確認をお願いします！

2021-07-26 08:22 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂

2022-02-17 12:22 UTC, merged