オブジェクト指向版のlsコマンド課題の提出
R-Tsukada/ruby-practices pull request #2
Opened 2021-07-08 00:52 UTC by R-Tsukada

オブジェクト指向版のlsコマンド課題を作成しました。
お手数ですがご確認をお願いします。

オブジェクト指向の考え方をあまり理解できていないと思います。
もし間違いがありましたらご指摘ください🙇‍♂️

よろしくお願いいたします。

2021-07-14 02:35 UTC, u1tnk requested changes
クラスの分けかたはとてもシンプルなオブジェクト指向になってるのでとても良いですね 👍 
FileListまでがあくまで情報収集で、Formatに出力関係を集約して分割してるのも良いと思います 👍 

細かい指摘をいくつかしていますので確認ください。

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/ls_command.rb
> +ls_file_list = FileList.new(pathname, reverse: reverse, dot_match: dot_match)
すごく細かいですけど、`ls_` は不要かなと。ファイル名からcontextは分か

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  attr_reader :long_style, :file_list
これは外部から読むためのものなので、内部設定的に使うのであればインスタンス変数だけで良いですよ。

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def initialize(pathname, reverse: false, dot_match: false)
基本的に単語の切れ目は snakecaseなのに  pathnameと filenameだけ繋がってるのが気になります。
どこかでそういうメソッドがあったとかですかね？
おそらくはそういうのはC言語とかlinuxのコマンド名由来とか(rubyにもちょくちょくありますね)のものなので、自作プログラムでマネしなくても大丈夫ですよ。

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def filename
このメソッドはどこかで使ってますか？
grepした感じ無いかと思ったのですが、同名のメソッドがあるので見逃していたらすみません。
もし使ってないなら、使ってないメソッドは使いそうと思っても作らなくて良いです。
基本的には yagni原則で良いと思います。 https://ja.wikipedia.org/wiki/YAGNI#:~:text=%22You%20ain't%20gonna%20need,%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%8E%9F%E5%89%87%E3%81%A7%E3%81%82%E3%82%8B%E3%80%82

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def filename
また、結局filenameの配列を返すので メソッド名も `file_names`の方が良いと思い

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def file_data
あー、dataは複数形無いからそのままなんですね。
ここは人によるところですが、複数形が無い単語を使うと、こういうときに中身が配列なのか判別が付きづらいので、個人的には避けますね 🤔

2021-07-14 02:35 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def file_data
あくまで僕ならですが、複数形にするために ls というmodule名でかこんでしまって `Ls::File` というクラスにすると思います。

2021-07-16 02:04 UTC, R-Tsukada commented on 08.ls_object/lib/ls_command.rb
> +ls_file_list = FileList.new(pathname, reverse: reverse, dot_match: dot_match)
たしかに`ls`表記がなくても意味は理解できますね💦
`ls_`を削除しました！

2021-07-16 02:04 UTC, R-Tsukada commented on 08.ls_object/lib/file_list.rb
> +  attr_reader :long_style, :file_list
アクセサメソッドを削除しました！

2021-07-16 02:05 UTC, R-Tsukada commented on 08.ls_object/lib/file_list.rb
> +  def initialize(pathname, reverse: false, dot_match: false)
正直、あまり考えずにメソッド名をつけていました💦
メソッド名の命名基準を統一しました。

2021-07-16 02:06 UTC, R-Tsukada commented on 08.ls_object/lib/file_list.rb
> +  def filename
このメソッドは使っています。同じメソッド名があり、わかりにくくなってしまい申し訳ありません。
メソッド名を変更しましたので再度ご確認をしてもらえたらと思います🙇‍♂️

> 結局filenameの配列を返すので メソッド名も file_namesの方が良いと思い
`file_names`に変更しました！

2021-07-16 02:10 UTC, R-Tsukada commented on 08.ls_object/lib/file_list.rb
> +  def file_data
> あー、dataは複数形無いからそのままなんですね。
ここは人によるところですが、複数形が無い単語を使うと、こういうときに中身が配列なのか判別が付きづらいので、個人的には避けますね 🤔

他のメソッド名が思いつかなかったので安易に`data`を使ってしまいました💦
`file_contents`というメソッド名に変更してみたのですが、いかがでしょうか？

> あくまで僕ならですが、複数形にするために ls というmodule名でかこんでしまって Ls::File というクラスにすると思います。

これは`file_data`を複数形にするためにmoduleを使うということでよろしかったでしょうか？
moduleを使うことで`file_data`を複数形にできる、ということが理解できませんでした💦

2021-07-16 03:08 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def filename
なるほど。使ってましたね。

2021-07-16 03:14 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def file_data
説明不足ですみません。
本当はFileと付けたいけど、重複するのでFileDataとしたんだと思っていて、それを解消するために

FIleDataクラスを `Ls::File`クラスにすれば、ここも `files`なり `ls_files`となるかなと思って書きました。

file_contentsというメソッドで file_dataクラスの配列が入ってくるのはちょっと混乱すると思います 🤔 

あと、contentsという単語はwebプログラム的には「中身」という意味でよく使われているのでこの場合は適さないと思います。 例えばhttpヘッダだと Content-Lengthってあると思いますが、この場合のContentはヘッダとかメタデータになるところは含まずに中身を指す言葉となります。

2021-07-22 02:12 UTC, R-Tsukada commented on 08.ls_object/lib/file_list.rb
> +  def file_data
クラス名とメソッド名を変更しました！ご確認をお願いします🙇‍♂️
moduleを使わなかったのですが、使った方がいいのでしょうか？

> contentsという単語はwebプログラム的には「中身」という意味でよく使われているのでこの場合は適さないと思います。 例えばhttpヘッダだと Content-Lengthってあると思いますが、この場合のContentはヘッダとかメタデータになるところは含まずに中身を指す言葉となります。

ファイルのリンクや所有者などの情報がcontentsに近いのかな、と考えたのですが、わかりにくいんですね！
勉強になりました！ありがとうございます！

2021-07-22 14:08 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def file_data
ただの例なので module使っても現状の `LsFile`でもどっちでも良いですよ 👍

2021-07-22 14:09 UTC, u1tnk requested changes
確認しました。良いと思います 👍

2022-02-17 12:22 UTC, merged